### ISSUE TITLE
Recommended improvements

### ISSUE THREAD

**Issue by mihapompe** [bkurit/AirBNB-sales-analysis#1]
There are a few things that still have to be changed in order to make your project more presentable.
- Change the name of the repository to AirBNB sales analysis, B2B sales analysis was the name of a different project.
- Modify the readme.md file, the reader should know what is your project, how to run it and what were your conclusions.
- Upload a PDF version of your report. Word documents can be formatted differently on differet computers and you want the viewers to see the report the way you designed it.
- In the Python file uncomment the code parts.

When you finish all these mark this issue as solved.

**Comment by bkurit** [comment]
Fixed
